version: '2'
services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
      - 8010:8010  # Using default port from the image
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=256m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=512m  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - /Users/ppham/Documents/Phi/git/languagetool:/ngrams
  media-services:
    image: pppham/media-services:1.0.2
    container_name: media-services
    ports:
      - 3000:3000
    environment:
      - SENDGRID_API_KEY=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
      - SENDGRID_MAIL_FROM=admin@pteleader.com.au
      - WIT_API_KEY=AW35CXSW7TKSFKSYB2ZUWEOMFBJSGK2X
      - TEXT_ANALYSIS_URL=http://languagetool:8010/v2/check
      - JWT_SECRET=qQm8Pxj+drc6uGbyQl5m9DqPH682ZP2DKdl1UN53
      - JWT_ISSUER=http://localhost:8080
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=dev
      - DB_NAME=moodle
    volumes:
      - ./src/server.js:/usr/src/app/src/server.js
